### ISSUE TITLE
Document commands

### ISSUE THREAD

**Issue by johnslavik** [coherent-oss/coherent.cli#3]
Pretty important for a jump-start DX

**Comment by jaraco** [comment]
The commands are illustrated in the [system](/coherent-oss/system). I want to be cautious about where to document them as I don't want to maintain too much overlapping guidance in different places. At the very least, this project should refer to the coherent system.

**Comment by jaraco** [comment]
I started working on linking to the system and I realized I'd really like not to have to create a README.md. For a project as small as this, a docstring in `__init__` should suffice (https://github.com/coherent-oss/system/issues/10). But since that issue isn't solved, the only good choice is a README file, so I'll do that for now.
